yatube/about/urls.py
from django.urls import path
from . import views


app_name = 'about'

urlpatterns = [
    path('author/', views.AboutAuthorView.as_view(), name='author'),
    path('tech/', views.AboutTechView.as_view(), name='tech'),
]

yatube/posts/urls.py
from django.urls import path
from . import views

app_name = 'posts'

urlpatterns = [
    path('', views.index, name='index'),
    path('group/<slug:slug>/', views.group_posts, name='group_list'),
    path('profile/<str:username>/', views.profile, name='profile'),
    path('posts/<int:post_id>/', views.post_detail, name='post_detail'),
]

yatube/users/urls.py
from django.contrib.auth.views import LoginView, LogoutView, PasswordResetView
from django.urls import path

from . import views

app_name = 'users'

urlpatterns = [
    path('signup/', views.SignUp.as_view(), name='signup'),
    path(
        'logout/',
        LogoutView.as_view(template_name='users/logged_out.html'),
        name='logout'
    ),
    path(
        'login/',
        LoginView.as_view(template_name='users/login.html'),
        name='login'
    ),
    path(
        'password_reset/',
        PasswordResetView.
        as_view(template_name='users/password_reset_form.html'),
        name='password_reset'
    )
]

yatube/yatube/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('', include('posts.urls', namespace='posts')),
    path('auth/', include('users.urls', namespace='users')),
    path('about/', include('about.urls', namespace='about')),
    path('auth/', include('django.contrib.auth.urls')),
    path('admin/', admin.site.urls),
]

yatube/about/models.py
from django.db import models

# Create your models here.

yatube/posts/models.py
from django.db import models
from django.contrib.auth import get_user_model

User = get_user_model()


class Post(models.Model):
    text = models.TextField()
    pub_date = models.DateTimeField(auto_now_add=True)
    author = models.ForeignKey(
        User,
        null=True,
        on_delete=models.SET_NULL,
        related_name='posts'
    )
    group = models.ForeignKey(
        'Group',
        blank=True,
        null=True,
        on_delete=models.CASCADE,
        related_name='posts'
    )

    class Meta:
        ordering = ['-pub_date']

    def __str__(self):
        return self.text


class Group(models.Model):
    title = models.CharField(max_length=200)
    slug = models.SlugField(unique=True)
    description = models.TextField()

    def __str__(self) -> str:
        return f'Group{self.title}'

yatube/users/models.py
# from django.db import models

# Create your models here.

yatube/users/forms.py
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth import get_user_model

User = get_user_model()


class CreationForm(UserCreationForm):
    class Meta(UserCreationForm.Meta):
        model = User
        fields = ('first_name', 'last_name', 'username', 'email')

yatube/about/views.py
from django.views.generic.base import TemplateView


class AboutAuthorView(TemplateView):
    template_name = 'about/author.html'


class AboutTechView(TemplateView):
    template_name = 'about/tech.html'

yatube/posts/views.py
from django.shortcuts import get_object_or_404, render

from django.core.paginator import Paginator

from .models import Group, Post, User

NUMBERS_POSTS_ON_PAGES = 10


def index(request):
    post_list = Post.objects.all()
    paginator = Paginator(post_list, 10)
    page_number = request.GET.get('page')
    page_obj = paginator.get_page(page_number)
    context = {
        'page_obj': page_obj,
    }
    return render(request, 'posts/index.html', context)


def group_posts(request, slug):
    group = get_object_or_404(Group, slug=slug)
    post_list = Post.objects.filter()[:NUMBERS_POSTS_ON_PAGES]
    paginator = Paginator(post_list, 10)
    page_number = request.GET.get('page')
    page_obj = paginator.get_page(page_number)
    context = {
        'page_obj': page_obj,
        'group': group
    }
    return render(request, 'posts/group_list.html', context)


def profile(request, username):
    user = get_object_or_404(User, username=username)
    posts = user.posts.all()
    posts_count = posts.count()
    paginator = Paginator(posts, NUMBERS_POSTS_ON_PAGES)
    page_number = request.GET.get('page')
    page_obj = paginator.get_page(page_number)
    title = f'Профайл пользователя {user.username}'
    context = {
        'user': user,
        'post_list': posts,
        'page_obj': page_obj,
        'posts_count': posts_count,
        'title': title
    }
    return render(request, 'posts/profile.html', context)


def post_detail(request, post_id):
    post = get_object_or_404(Post, id=post_id)
    posts_list = (Post.objects.select_related('author')
                  .filter(author=post.author))
    posts_count = posts_list.count()
    context = {
        'post': post,
        'posts_count': posts_count
    }
    return render(request, 'posts/post_detail.html', context)

yatube/users/views.py
from django.views.generic import CreateView

from django.urls import reverse_lazy

from .forms import CreationForm


class SignUp(CreateView):
    form_class = CreationForm
    success_url = reverse_lazy('posts:index')
    template_name = 'users/signup.html'


class PasswordResetView(CreateView):
    form_class = CreationForm
    success_url = reverse_lazy('posts:index')
    template_name = 'users/password_reset_form.html'

yatube/templates/about/author.html
{% extends "base.html" %}
{% load static %}
{% block title %}
  <title>Об авторе проекта</title>
{% endblock %}
{% block content %}
<div class="container">
<center><h1>Привет, я автор. Меня зовут Анастасия!</h1></center>
<p>
   Hello, my dear guest!
   Давайте познакомимся? 
   Я расскажу о себе пару фактов:
  <ul>
    <li>Мне 23</li>
    <li>Я живу в Москве</li>
    <li>Решила заняться программированием</li>
  </ul>
  <a href="https://github.com/AnastasiyaKap">
        А это мой GitHub, где я делаю свои проекты. Вы тоже можете зайти
        и посмотреть что там!</br>
  </a>
    В свободное время я работаю,
    мне нравится заниматься английским языком,
    а также я учусь программировать.
  <div>
    <img src="{% static 'img/my_table.jpg' %}" width="250px" 
    hspace="20px" vspace="15px" alt="Мой рабочий стол">
  </div>
  <p>
    Теперь давай познакомимся с тобой</br>
    Расскажи мне немного о себе:
    Чем увлекаешься? От куда ты?</br>
    Нравится ли тебе программирование?</br>
    </p>
</p>
</div>
{% endblock %} 

yatube/templates/about/tech.html
{% extends "base.html" %}
{% block title %}<title>Технологии</title>{% endblock %}
{% block content %}
<div class="row">
  <center><h1>Вот что я умею</h1></center>
  <aside class="col-12 col-md-3">
    <ul class="list-group list-group-flush">
      <li class="list-group-item">
        Python
      </li>
      <li class="list-group-item">
        Django
      </li>
    </ul>
  </aside>
  <article class="col-12 col-md-9">
    <p>
      Для создания этого сайта я использовала знания
      HTML, CSS, Python, а также Django.</br>
      Декораторы - тема, которую в теории я 
      поняла, а на практике всё намного сложнее.</br>
      Лучше всего я поняла синтаксис работы Django.
      Мир программировия сложный, но увлекательный!</br>
      Также я научилась работать в терминале GitBash
      Все свои проекты я выкладываю в свой аккаунт GitHub</br>
      Я мечтаю научиться кодить и дойти до Middle-разработчика.
    </p>
  </article>
</div>
{% endblock %} 

yatube/templates/base.html
{% load static %}
<!DOCTYPE html> 
<html lang="ru">          
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="icon" href="{% static 'img/fav/fav.ico' %}" type="image">
    <link rel="apple-touch-icon" sizes="180x180" href="{% static 'img/fav/apple-touch-icon.png' %}">
    <link rel="icon" type="image/png" sizes="32x32" href="{% static 'img/fav/favicon-32x32.png' %}">
    <link rel="icon" type="image/png" sizes="16x16" href="{% static 'img/fav/favicon-16x16.png' %}">
    <meta name="msapplication-TileColor" content="#000">
    <meta name="theme-color" content="#FFFFFF">
    <link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}">
  </head>
{% block title %}
  Ошибка
{% endblock %}        
 <header>
    {% include 'includes/header.html' %}
 </header>
    <main>
      {% block content %}
        Ошибка
      {% endblock content %}
    </main>
  <footer>
    {% include 'includes/footer.html' %} 
  </footer>
</html> 

yatube/templates/includes/description.html
<ul>
  <li>
    Автор: {{ post.author.get_full_name }}
  </li>
  <li>
    Дата публикации: {{ post.pub_date|date:"d E Y" }}
  </li>
</ul>      
<p>
  {{ post.text }}
 </p>
{% if post.group %}    
  <a href="{% url 'posts:group_list' post.group.slug %}">все записи группы</a> 
{% endif %}  
{% if not forloop.last %}<hr>{% endif %}
   
 

yatube/templates/includes/footer.html
<div class="footer-copyright text-center py-3">© {{ year }} Copyright 
    <p><span style="color:red">Ya</span>tube</p> 
  </div>  

yatube/templates/includes/header.html
{% load  static %}
<link rel ="stylesheet" href="{% static 'css/bootstrap.min.css' %}">
  <nav class="navbar navbar-light" style="background-color: lightskyblue">
    <div class="container">
      <a class="navbar-brand" href="{% url 'posts:index' %}">
        <img src="{% static 'img/logo.png' %}" width="30" height="30" class="d-inline-block align-top" alt="">
          <span style="color:red">Ya</span>tube
      </a>
    </div>
  </nav>
  <ul class="nav nav-pills">
    <li class="nav-item"> 
      <a class="nav-link" href={% url 'about:author' %}>Об авторе</a>
    </li>
    <li class="nav-item">
      <a class="nav-link" href={% url 'about:tech' %}>Технологии</a>
    </li>
    {% if user.is_authenticated %}
    user.is_authenticated
    <li class="nav-item"> 
      <a class="nav-link" href="<!--  -->">Новая запись</a>
    </li>
    <li class="nav-item"> 
      <a class="nav-link link-light" href={% url 'users:password_reset' %}>Изменить пароль</a>
    </li>
    <li class="nav-item"> 
      <a class="nav-link link-light" href={% url 'users:logged_out' %}>Выйти</a>
    </li>
    <li>
      Пользователь: {{ user.username }}
    </li>
    {% else %}
    <li class="nav-item"> 
      <a class="nav-link link-light" href={% url 'users:login' %}>Войти</a>
    </li>
    <li class="nav-item"> 
      <a class="nav-link link-light" href={% url 'users:signup' %}>Регистрация</a>
    </li>
  </ul>
  {% endif %}
</div>
</nav>      
</header>     

yatube/templates/includes/text_post.html
<ul>
  <li>
    Автор: {{ post.author.get_full_name }}
  </li>
  <li>
    Дата публикации: {{ post.pub_date|date:"d E Y" }}
  </li>
</ul>      
<p>
  {{ post.text }}
</p>  
{% if not forloop.last %}<hr>{% endif %}

yatube/templates/posts/group_list.html
{% extends 'base.html' %} 
{% block title %}
  <title>Записи сообщества</title>
{% endblock %}
{% block content %}
<div class="container">
  <h1>Лев Толстой - зеркало русской души</h1>
  <p>
    Группа тайных поклонников графа.
  </p>
  <article>
    {% for post in page_obj %}
    {% include 'includes/text_post.html' %}    
    {% endfor %} 
    {% include 'posts/includes/paginator.html' %}
  </article>
  <!-- под последним постом нет линии -->
</div>  
{% endblock content %}

yatube/templates/posts/includes/paginator.html
{% if page_obj.has_other_pages %}
<nav aria-label="Page navigation" class="my-5">
  <ul class="pagination">
    {% if page_obj.has_previous %}
      <li class="page-item"><a class="page-link" href="?page=1">Первая</a></li>
      <li class="page-item">
        <a class="page-link" href="?page={{ page_obj.previous_page_number }}">
          Предыдущая
        </a>
      </li>
    {% endif %}
    {% for i in page_obj.paginator.page_range %}
        {% if page_obj.number == i %}
          <li class="page-item active">
            <span class="page-link">{{ i }}</span>
          </li>
        {% else %}
          <li class="page-item">
            <a class="page-link" href="?page={{ i }}">{{ i }}</a>
          </li>
        {% endif %}
    {% endfor %}
    {% if page_obj.has_next %}
      <li class="page-item">
        <a class="page-link" href="?page={{ page_obj.next_page_number }}">
          Следующая
        </a>
      </li>
      <li class="page-item">
        <a class="page-link" href="?page={{ page_obj.paginator.num_pages }}">
          Последняя
        </a>
      </li>
    {% endif %}    
  </ul>
</nav>
{% endif %}

yatube/templates/posts/index.html
{% extends 'base.html' %} 
{% block title %}
  <title>Последние объявления на сайте</title>
{% endblock %}  
{% block content %}
<div class="container">
  <div class="container py-5">
    {% for post in page_obj %}     
    {% include 'includes/description.html' %}
    {% endfor %}  
    {% include 'posts/includes/paginator.html' %}
  </div> 
</div> 
{% endblock content %}

yatube/templates/posts/post_detail.html
{% extends 'base.html' %}
{% block title %} <title>Пост{{ post.text|truncatechars:30 }}</title> {% endblock %}
 {% block content %}
      <div class="row">
        <aside class="col-12 col-md-3">
          <ul class="list-group list-group-flush">
            <li class="list-group-item">
              Дата публикации: {{ post.pub_date|date:"d E Y" }} 
            </li>
            {% if post.group %}
              <li class="list-group-item">
                Группа: {{ post.group }}
              <a href={% url 'posts:group_list' post.group.slug %}>
                все записи группы
              </a>
              </li>
            {% endif %}
            <li class="list-group-item">
              Автор: {{ post.author.get_full_name }} 
            </li>
            <li class="list-group-item d-flex justify-content-between align-items-center">
              Всего постов автора:  <span >{{ posts_count }}</span>
            </li>
            <li class="list-group-item">
            <a href={% url 'posts:profile' post.author.username %}
              все посты пользователя
            </a>
            </li>
          </ul>
        </aside>
        <article class="col-12 col-md-9">
          <p>{{ post.text }} </p>
          {% include 'posts/includes/paginator.html' %}
        </article>
      </div> 
  {% endblock %}

yatube/templates/posts/profile.html
{% extends 'base.html' %}    
{% block title %}<title>Профайл пользователя {{ user }} </title> {% endblock %}
  {% block content %}
      <div class="container py-5">        
        <h1>Все посты пользователя {{ user}} </h1>
          <h3>Всего постов: {{ posts_count }}  </h3>   
            <article>
              {% for post in page_obj %}
                  <ul>
                    <li>
                      Автор: {{ post.author.get_full_name }} 
                      <a href={% url 'posts:profile' user.username %} >все посты пользователя</a>
                    </li>
                    <li>
                      Дата публикации: {{ post.pub_date|date:"d E Y" }} 
                    </li>
                  </ul>
                    <p>{{ post.text }} </p>
                    <a href={% url 'posts:post_detail' post.id %}>подробная информация </a>
                    {% if post.group %}     
                    <a href={% url 'posts:group_list' post.group.slug %}>все записи группы</a>  
                    {% endif %}   
                    {% if not forloop.last %}<hr>{% endif %}
                    {% endfor %}
                    {% include 'posts/includes/paginator.html' %}
            </article>
    </div>
  {% endblock %}

yatube/templates/users/logged_out.html
{% extends 'base.html' %}
{% block title %}<title>Вы вышли из системы</title>{% endblock %}
{% block content %}
<div class="row justify-content-center">
  <div class="col-md-8 p-5">
    <div class="card">
      <div class="card-header">
        Выход
      </div>
      <div class="card-body">
        <p>
          Вы вышли из своей учётной записи. Ждём вас снова!
        </p>
      </div> <!-- card body -->
    </div> <!-- card -->
  </div> <!-- col -->
</div> <!-- row -->
{% endblock %} 

yatube/templates/users/login.html
{% extends "base.html" %}
{% block title %}<title>Войти</title>{% endblock %}
{% block content %}
{% load user_filters %}
  <div class="row justify-content-center">
    <div class="col-md-8 p-5">
      <div class="card">
        <div class="card-header">
          Войти на сайт
        </div>
        <div class="card-body">
          {% if form.errors %}
              {% for field in form %}
                {% for error in field.errors %}            
                  <div class="alert alert-danger">
                    {{ error|escape }}
                  </div>
                {% endfor %}
              {% endfor %}
              {% for error in form.non_field_errors %}
                <div class="alert alert-danger">
                  {{ error|escape }}
                </div>
              {% endfor %}
          {% endif %}

          <form method="post"
            {% if action_url %}
              action="{% url action_url %}"
            {% endif %}
          >
          {% csrf_token %}

          {% for field in form %}
            <div class="form-group row my-3"
              {% if field.field.required %} 
                aria-required="true"
              {% else %}
                aria-required="false"
              {% endif %}
            >
              <label for="{{ field.id_for_label }}">
                {{ field.label }}
                  {% if field.field.required %}
                    <span class="required text-danger">*</span>
                  {% endif %}
              </label>
              <div>
              {{ field|addclass:'form-control' }}
                {% if field.help_text %}
                  <small id="{{ field.id_for_label }}-help" class="form-text text-muted">
                    {{ field.help_text|safe }}
                  </small>
                {% endif %}
              </div>
            </div>
          {% endfor %}
          <div class="col-md-6 offset-md-4">
            <button type="submit" class="btn btn-primary">
              Войти
            </button>
            <!-- Тест на внимательность. Без переопределения шаблона этого адреса
            не существует. Нужно что-то делать, иначе все упадет -->
            <a href={% url 'users:password_reset' %} class="btn btn-link">
              Забыли пароль?
            </a>
          </div>
          </form>
        </div> <!-- card body -->
      </div> <!-- card -->
    </div> <!-- col -->
</div> <!-- row -->
{% endblock %}

yatube/templates/users/password_reset_form.html
{% extends "base.html" %}
{% block title %}<title>Сброс пароля</title>{% endblock %}
{% block content %}
    <main>
      <div class="container py-5"> 
        <div class="row justify-content-center">
          <div class="col-md-8 p-5">
            <div class="card">
              <div class="card-header">
                Чтобы сбросить старый пароль — введите адрес электронной почты, под которым вы регистрировались
              </div>
              <div class="card-body"> 
                <form method="post" action="../users/password_reset_form.html">
                  <input type="hidden" name="csrfmiddlewaretoken" value="">
                  <div class="form-group row my-3 p-3">
                    <label for="id_email">
                      Адрес электронной почты
                      <span class="required text-danger">*</span>
                    </label>    
                    <input type="email" name="email" maxlength="254" class="form-control" required id="id_email">
                  </div>
                  <div class="col-md-6 offset-md-4">
                    <button type="submit" class="btn btn-primary">
                      Сбросить пароль
                    </button>
                  </div>
                </form>
              </div>
            </div>
          </div>
        </div>  
      </div>
    </main>
{% endblock %}

yatube/templates/users/signup.html
{% extends "base.html" %}
{% block title %}<title>Зарегистрироваться</title>{% endblock %}
{% block content %}
  <div class="row justify-content-center">
    <div class="col-md-8 p-5">
      <div class="card">
        <div class="card-header">Зарегистрироваться</div>
          <div class="card-body">
          {% load user_filters %} 
              {% if form.errors %}
                  {% for field in form %} 
                    {% for error in field.errors %}            
                      <div class="alert alert-danger">
                        {{ error|escape }}
                      </div>
                    {% endfor %}
                  {% endfor %}
                  {% for error in form.non_field_errors %}
                    <div class="alert alert-danger">
                      {{ error|escape }}
                    </div>
                  {% endfor %}
              {% endif %}

              <form method="post" action="{% url 'users:signup' %}">
              {% csrf_token %}

              {# Выводим поля в цикле, по отдельности #}
              {% for field in form %} 
                <div class="form-group row my-3">
                  <label for="{{ field.id_for_label }}">
                    {{ field.label }}
                      {% if field.field.required %}
                        <span class="required text-danger">*</span>
                      {% endif %}
                  </label>
                  {# К полю ввода добавляем атрибут class #}
                  {{ field|addclass:'form-control' }} 
                    {% if field.help_text %}
                      <small 
                         id="{{ field.id_for_label }}-help"
                         class="form-text text-muted"
                      >
                        {{ field.help_text|safe }}
                      </small>
                    {% endif %}
                </div>
              {% endfor %}
              <div class="col-md-6 offset-md-4">
                <button type="submit" class="btn btn-primary">
                  Зарегистрироваться
                </button>
              </div>
            </form>
          </div> <!-- card body -->
        </div> <!-- card -->
      </div> <!-- col -->
  </div> <!-- row -->
{% endblock %}